### ISSUE TITLE
Sistem Gereksinimleri 

### ISSUE THREAD

**Issue by alperenbolat** [alperenbolat/BBM487-20142-6#1]
Sistemle ilgili gereksinimleri ve kısıtları (varsa varsayımlarınız ile birlikte) belirtiniz.  (Requirements Specification)

**Comment by kivannc** [comment]
Pardon beni yanlislikla eklediniz galiba. Neler oluyor benim hicbir fikrim yok 





Kivanc ERTURK
erturkkivanc@gmail.com

**Comment by iarslanbay** [comment]
Projede bulunması gereken bütün sistem gereksinimleri, ayrıntılı bir şekilde raporlandı. Fonksiyonel gereksinimlerin yanında fonksiyonel olmayan performans, güvenlik, kullanılabilirlik gibi gereksinimler de açıklandı. Ayrıca projedeki kısıtlamalar ve varsayımlar da rapora eklendi.
İsmail ARSLANBAY
