### ISSUE TITLE
Teslimatlar Öncesi Ve Sonrası Mali Durum Tabloları

### ISSUE THREAD

**Issue by alperenbolat** [alperenbolat/BBM487-20142-6#10]
12 haftalık proje süreci boyunca her haftalık giderler ve proje teslimlerinde alınan primlerle birlikte  haftalık durum çizelgesini gösterecek tablo  hazırlanacaktır .

**Comment by zuleyhaipek** [comment]
Bu görev kısmında Mustafa Alperen BOLAT ve ben (Züleyha İPEK) durum raporu hazırladık. İçerisinde teslimat raporlarının ilerleme durumu, çalışma süresi, karşılaşılan problemler ve proje mali durum belirtilmiştir.
