### ISSUE TITLE
Proje Toplantıları Ve Alınan Kararlar 

### ISSUE THREAD

**Issue by alperenbolat** [alperenbolat/BBM487-20142-6#7]

**Comment by zuleyhaipek** [comment]
16.03.2015 toplantı
*vizyon raporunun üzerine konuşuldu ve uygun yazılım geliştirme süreci olarak waterfall seçildi
*process aktiviteler üzerinde tartışıldı ve belirlendi
*Teslimat sayısı ve zamanları belirlendi
*Verilen kararlar üzerine proje planlaması yapıldı.
*Proje planı rapor görev dağılımı yapıldı.
