### ISSUE TITLE
Proje Planında Yapılacaklar

### ISSUE THREAD

**Issue by alperenbolat** [alperenbolat/BBM487-20142-6#8]
Aktiviteler  , Süreler , Sorumlular ve Girdi/Çıktılar

**Comment by Merve7** [comment]
Projenin ve ödev tesliminin bu kısmında ben (Merve Özçifçi) grup arkadaşlarımdan Elif Yoldaş ile çalıştım.Derste işlenenleri ve kaynak kitabın 2.chapter kısmını baz alarak bundan sonraki aşamada yapılacak aktiviteleri açıkladık. Ayrıca sorumlulukların ne olduğuna değinip açıklamasını yaptık. Süre ve girdi çıktı incelemesinde bulunduk.
