### ISSUE TITLE
Projenin Süreç Aşamaları

### ISSUE THREAD

**Issue by alperenbolat** [alperenbolat/BBM487-20142-6#9]
Teslimat öncesinde yapılacak faaliyetlerin raporlanması ve teslimatların içeriği

**Comment by SedaCibiceli** [comment]
Proje için toplantılarımızda belirlediğimiz teslimat planına göre belgede, yapacağımız teslimatların içeriğini ve her teslimata göre önceden hazırlanması gereken dökümanları detaylandırdım.
